### PR TITLE
Upgrade dev dependency `mkdirp` to `^2.1.2`

### PR DESCRIPTION
**Pull request by jeremymeng**

### CODE REVIEW

**Comment by jeremymeng** [comment]
@MaryGao any tips on fixing the smoke tests Check Git Tree failures?

**Comment by joheredi** [comment]
> @MaryGao any tips on fixing the smoke tests Check Git Tree failures?

I think these need to be updated as well: 

https://github.com/Azure/autorest.typescript/blob/d51bd1c7507f4a6630923ddf62fc8e2d20b5ab00/packages/rlc-common/src/metadata/buildPackageFile.ts#L153

https://github.com/Azure/autorest.typescript/blob/d51bd1c7507f4a6630923ddf62fc8e2d20b5ab00/packages/autorest.typescript/src/generators/static/packageFileGenerator.ts#L116

**Comment by jeremymeng** [comment]
> I think these need to be updated as well:

Thanks @joheredi! Not sure how my search missed these

**Review by deyaaeldeen — APPROVED** [review]
Thanks for upgrading us👍

**Pull request merged**
