### PR TITLE
Upgrading prettier to version 2.5.1 in packageFileGenerator

### PR DESCRIPTION
**Pull request by JonathanCrd**
Solves https://github.com/Azure/autorest.typescript/issues/1270

Upgrading prettier dev-dependency from `^2.2.1` to `^2.5.1` for generated packages.

### CODE REVIEW

**Comment by JonathanCrd** [comment]
This PR is ready for review, the only manual change was on "PackageFileGenerator.ts". All the other changes are generated.

**Comment by ramya-rao-a** [comment]
@JonathanCrd In #1264, we already merged the changes to the copyright... Can you get the changes from main and update this PR so that we have only the prettier related changes in the diff?

**Comment by JonathanCrd** [comment]
> @JonathanCrd In #1264, we already merged the changes to the copyright... Can you get the changes from main and update this PR so that we have only the prettier related changes in the diff?

Sure thing :)

**Review by ramya-rao-a — APPROVED** [review]

**Pull request merged**
