### PR TITLE
[v5] Update autorest.common

### PR DESCRIPTION
**Pull request by joheredi**
Updating Autorest.Common submodule to pickup the last 2 fixes:
1. Updating MIT License header (https://github.com/Azure/autorest.common/pull/57)
2. Keep Query params when creating a Next paging operation (https://github.com/Azure/autorest.common/pull/58)

All the changes in the generated test libraries in this PR are the result of (1), (2) doesn't have a direct impact in any of the generated test libraries

### CODE REVIEW

**Comment by deyaaeldeen** [comment]
would you mind sharing the list of files I should look at?

**Comment by joheredi** [comment]
@deyaaeldeen all the changes are in the License Headers there are no functional changes in the generated libraries. So just looking at a single test library should be enough. For example `test/azure/generated/AzureCompositeModelClient/*`

**Review by deyaaeldeen — APPROVED** [review]
Looks good!

**Pull request merged**
