### PR TITLE
Handle MapperType.Sequence in the Parameters

### PR DESCRIPTION
**Pull request by sarangan12**
This PR is to address the issue reported in https://github.com/Azure/autorest.typescript/issues/826. A detailed description of the issue is already provided in https://github.com/Azure/autorest.typescript/issues/826#issuecomment-764451828

@joheredi Please review and approve.

@ramya-rao-a FYI....

### CODE REVIEW

**Review by joheredi — COMMENTED** [review]
The change looks good, thanks for taking the time to fix this issue. While you are working around the schemas, would it be possible to try integrating fixes in this PR for:

https://github.com/Azure/autorest.typescript/pull/823

and

https://github.com/Azure/autorest.typescript/issues/824

**Comment by sarangan12** [comment]
824 is already on my radar. Needs a little more testing. I will resolve that soon. 

823 is not an issue. It is a PR which looks fine. We can merge it if it is tested. Will discuss with you offline about it. 

Currently merging this PR.

**Comment by sarangan12** [comment]
I see what you mean regarding 823. Will fix it now in this PR

**Comment by joheredi** [comment]
> I see what you mean regarding 823. Will fix it now in this PR

Great! Thank you

**Review by joheredi — APPROVED** [review]
Thanks for working on this!

**Pull request merged**
