### PR TITLE
Add Mgmt Azure Fleet

### PR DESCRIPTION
**Pull request by v-jiaodi**
image

### CODE REVIEW

**Comment by kazrael2119** [comment]
new:
removed XXXHeaders https://github.com/Azure/azure-sdk-for-js/blob/9488fe4bd780306e2f00eaa1509eba20982215f4/sdk/computefleet/arm-computefleet/src/models/index.ts#L1202-L1206

removed model XXXPropertiesUpdate: [code from swagger](https://github.com/Azure/azure-sdk-for-js/blob/9488fe4bd780306e2f00eaa1509eba20982215f4/sdk/computefleet/arm-computefleet/src/models/index.ts#L996-L1041) and[ code from modular
](https://github.com/v-jiaodi/autorest.typescript/blob/317fc59c5c26ace4df6eaecbb4915b9fe31fbd98/packages/typespec-test/test/AzureFleet.Management/generated/typespec-ts/src/models/models.ts#L220-L229)swagger link: https://github.com/Azure/azure-rest-api-specs/blob/f1546dc981fa5d164d7ecd13588520457462c22c/specification/azurefleet/resource-manager/Microsoft.AzureFleet/preview/2024-05-01-preview/azurefleet.json#L719-L723
tsp link:https://github.com/v-jiaodi/autorest.typescript/blob/317fc59c5c26ace4df6eaecbb4915b9fe31fbd98/packages/typespec-test/test/AzureFleet.Management/spec/fleet.tsp#L34-L47

Missing value of parameter baseVirtualMachineProfile in modular:

- baseVirtualMachineProfile in code generated from swagger: https://github.com/Azure/azure-sdk-for-js/blob/9488fe4bd780306e2f00eaa1509eba20982215f4/sdk/computefleet/arm-computefleet/src/models/index.ts#L1044-L1045
value of baseVirtualMachineProfile  in code generated from swagger:https://github.com/Azure/azure-sdk-for-js/blob/9488fe4bd780306e2f00eaa1509eba20982215f4/sdk/computefleet/arm-computefleet/src/models/index.ts#L211-L212 

- baseVirtualMachineProfile in code generated from modular: https://github.com/v-jiaodi/autorest.typescript/blob/317fc59c5c26ace4df6eaecbb4915b9fe31fbd98/packages/typespec-test/test/AzureFleet.Management/generated/typespec-ts/src/models/models.ts#L130-L131
value of baseVirtualMachineProfile  in code generated from modular: https://github.com/v-jiaodi/autorest.typescript/blob/317fc59c5c26ace4df6eaecbb4915b9fe31fbd98/packages/typespec-test/test/AzureFleet.Management/generated/typespec-ts/src/models/models.ts#L147

- tsp link: https://github.com/v-jiaodi/autorest.typescript/blob/317fc59c5c26ace4df6eaecbb4915b9fe31fbd98/packages/typespec-test/test/AzureFleet.Management/spec/fleet.tsp#L117-L120

**Comment by kazrael2119** [comment]
model name of options are different only in Fleet:
hlc:
https://github.com/Azure/azure-sdk-for-js/pull/30085/files#diff-abfcab035003e5f61fe6b74355ad029627d8285b1a47ffaa08ea748730117b36R189
modular:
https://github.com/Azure/autorest.typescript/pull/2580/files#diff-70950c5a353cadcb9ebc731bc8f62d3552e926687471f3857777b8b78f783488R42

**Comment by kazrael2119** [comment]
model name changed from OperationListResult to PagedOperation, and parameter "value" become required:
hlc code:
https://github.com/Azure/azure-sdk-for-js/pull/30085/files#diff-9efffea217d616dc839175eaa4d93850de1d6148b60fb38b355eb4511a70d187R12-R23

modular code:
https://github.com/v-jiaodi/autorest.typescript/blob/317fc59c5c26ace4df6eaecbb4915b9fe31fbd98/packages/typespec-test/test/AzureFleet.Management/generated/typespec-ts/src/models/models.ts#L304

swagger link:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/azurefleet/resource-manager/Microsoft.AzureFleet/preview/2024-05-01-preview/azurefleet.json#L65-L66

tsp link:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/azurefleet/resource-manager/Microsoft.AzureFleet/preview/2024-05-01-preview/azurefleet.json#L65-L66

**Comment by qiaozha** [comment]
close it as we have pr in sdk repo.

**Pull request closed without merging**
