### PR TITLE
Updated Readme file

### PR DESCRIPTION
**Pull request by thecodejedi**
I added the information about how to add the credentials constructor as this is commonly needed in REST calls.

I also took the liberty to restructure the Usage category for better readability after adding another topic there.

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by thecodejedi** [comment]
I did not change any file that could affect the build .... @olydis

**Comment by olydis** [comment]
@thecodejedi no worries, I think CI didn't succeed before 😋 @amarzavery will know

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by amarzavery** [comment]
Yes dont worry about CI. The tests are passing locally.

**Pull request merged**
