### PR TITLE
Check bundle size

### PR DESCRIPTION
**Pull request by RikkiGibson**

### CODE REVIEW

**Comment by RikkiGibson** [comment]
Seeing this error when making a call to GitHub (maybe the get PR info call?):
```sh
403 - "{\"message\":\"At least one email address must be verified to do that.\",\"documentation_url\":\"https://help.github.com/articles/adding-an-email-address-to-your-github-account\"}"
```
@fearthecowboy could we get the email address for our CI bot verified?

**Comment by fearthecowboy** [comment]
Um... I would have thought that it was. 

Lemme see if I can see what's going on then.

**Comment by RikkiGibson** [comment]
I appreciate it. Maybe it's also possible that I'm not consuming the token/calling the API properly in my script?

**Comment by RikkiGibson** [comment]
Doesn't pass due to old gen code.. will rebase or something.

**Comment by RikkiGibson** [comment]
# 🤖 AutoRest automatic bundle size check 🤖
### Size increased by 0.00% (0 B)

**Comment by RikkiGibson** [comment]
@fearthecowboy I noticed a similar 403 error in the coverage check step--and also noticing that the bot is not posting coverage right now. Did our bot get deauthorized/flagged somehow by GitHub perhaps? https://devdiv.visualstudio.com/DevDiv/_build?buildId=1718497

**Pull request merged**
