### PR TITLE
Make CI pass and clean up test structure

### PR DESCRIPTION
**Pull request by RikkiGibson**
Suggest checking out c79ef33 in particular. Other commits are mainly file deletes and moves.

- Removes all generated .js and .js.map files from git
- Removes all child package.json files. npm seems to bake the assumption pretty deeply of "one git repo, one package.json" so attempts to keep child modules as one would in maven get clumsy
- Simplifies unit test configuration thanks to ts-node. Simply run `mocha` in the repo root to run tests, showing colorized output as each test completes, or `mocha -grep 'pattern'` to run only tests whose names match a certain pattern.
- Continues the practice of strictly checking generated code while loosely checking unit test cases. See [tsconfig.generated.json](https://github.com/Azure/autorest.typescript/blob/48daae2017f368511f23c97ce7328911e685d53c/test/tsconfig.generated.json).
  - gulp test enforces this with a `tsc -p ./test/tsconfig.generated.json` step.
- Simplified folder structure
- Removes unit.js and testlist.txt files.
  - I wanted to get away from ad-hoc methods of building up mocha arguments programmatically. After a considerable amount of searching the best way I could find to ensure the coverage report is run last in each suite was to simply name the coverage reporter file "zz_coverage.ts".

CI is failing because I need to publish a new version of ms-rest-js. Will restart Travis after I've published that.

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.4.2*

## ❌️ General: 94%

<details><summary>31 out of 535 features are not covered by tests</summary><p>

[`HttpRedirect301Put`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect301Put), [`HttpRedirect302Patch`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect302Patch), [`UrlQueriesArrayMultiEmpty`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiEmpty), [`UrlQueriesArrayMultiNull`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiNull), [`UrlQueriesArrayMultiValid`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiValid), [`additionalPropertiesInProperties`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInProperties), [`additionalPropertiesInPropertiesWithAPTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInPropertiesWithAPTypeString), [`additionalPropertiesTrue`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTrue), [`additionalPropertiesTypeObject`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeObject), [`additionalPropertiesTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeString), [`allowedValueEnum`](https://github.com/Azure/autorest.testserver/search?q=allowedValueEnum), [`animalNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=animalNotFoundError), [`expectedEnum`](https://github.com/Azure/autorest.testserver/search?q=expectedEnum), [`expectedNoErrors`](https://github.com/Azure/autorest.testserver/search?q=expectedNoErrors), [`expectedPetHungryError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetHungryError), [`expectedPetSadError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetSadError), [`getEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferenced), [`getEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferencedConstant), [`intError`](https://github.com/Azure/autorest.testserver/search?q=intError), [`linkNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=linkNotFoundError), [`putArrayDurationValid`](https://github.com/Azure/autorest.testserver/search?q=putArrayDurationValid), [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated), [`putComplexPolymorphismNoDiscriminator`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismNoDiscriminator), [`putComplexPrimitiveDuration`](https://github.com/Azure/autorest.testserver/search?q=putComplexPrimitiveDuration), [`putDictionaryDurationValid`](https://github.com/Azure/autorest.testserver/search?q=putDictionaryDurationValid), [`putDurationPositive`](https://github.com/Azure/autorest.testserver/search?q=putDurationPositive), [`putEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferenced), [`putEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferencedConstant), [`roundTripEnum`](https://github.com/Azure/autorest.testserver/search?q=roundTripEnum), [`stringError`](https://github.com/Azure/autorest.testserver/search?q=stringError), [`unexpectedEnum`](https://github.com/Azure/autorest.testserver/search?q=unexpectedEnum)</p></details>

## ❌️ Azure: 99%

<details><summary>1 out of 118 features are not covered by tests</summary><p>

[`LRONonRetryPut201Creating400InvalidJson`](https://github.com/Azure/autorest.testserver/search?q=LRONonRetryPut201Creating400InvalidJson)</p></details>

**Comment by RikkiGibson** [comment]
Note that I made travisci inactive because it has a hanging error and I don't want to spend time diagnosing it.

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.4.2*

## ❌️ General: 94%

<details><summary>27 out of 535 features are not covered by tests</summary><p>

[`HttpRedirect301Put`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect301Put), [`HttpRedirect302Patch`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect302Patch), [`UrlQueriesArrayMultiEmpty`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiEmpty), [`UrlQueriesArrayMultiNull`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiNull), [`UrlQueriesArrayMultiValid`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiValid), [`additionalPropertiesInProperties`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInProperties), [`additionalPropertiesInPropertiesWithAPTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInPropertiesWithAPTypeString), [`additionalPropertiesTrue`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTrue), [`additionalPropertiesTypeObject`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeObject), [`additionalPropertiesTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeString), [`allowedValueEnum`](https://github.com/Azure/autorest.testserver/search?q=allowedValueEnum), [`animalNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=animalNotFoundError), [`expectedEnum`](https://github.com/Azure/autorest.testserver/search?q=expectedEnum), [`expectedNoErrors`](https://github.com/Azure/autorest.testserver/search?q=expectedNoErrors), [`expectedPetHungryError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetHungryError), [`expectedPetSadError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetSadError), [`getEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferenced), [`getEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferencedConstant), [`intError`](https://github.com/Azure/autorest.testserver/search?q=intError), [`linkNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=linkNotFoundError), [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated), [`putComplexPolymorphismNoDiscriminator`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismNoDiscriminator), [`putEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferenced), [`putEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferencedConstant), [`roundTripEnum`](https://github.com/Azure/autorest.testserver/search?q=roundTripEnum), [`stringError`](https://github.com/Azure/autorest.testserver/search?q=stringError), [`unexpectedEnum`](https://github.com/Azure/autorest.testserver/search?q=unexpectedEnum)</p></details>

## ❌️ Azure: 99%

<details><summary>1 out of 118 features are not covered by tests</summary><p>

[`LRONonRetryPut201Creating400InvalidJson`](https://github.com/Azure/autorest.testserver/search?q=LRONonRetryPut201Creating400InvalidJson)</p></details>

**Comment by RikkiGibson** [comment]
> win32-x64 restart

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.4.2*

## ❌️ General: 94%

<details><summary>27 out of 535 features are not covered by tests</summary><p>

[`HttpRedirect301Put`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect301Put), [`HttpRedirect302Patch`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect302Patch), [`UrlQueriesArrayMultiEmpty`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiEmpty), [`UrlQueriesArrayMultiNull`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiNull), [`UrlQueriesArrayMultiValid`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiValid), [`additionalPropertiesInProperties`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInProperties), [`additionalPropertiesInPropertiesWithAPTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInPropertiesWithAPTypeString), [`additionalPropertiesTrue`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTrue), [`additionalPropertiesTypeObject`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeObject), [`additionalPropertiesTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeString), [`allowedValueEnum`](https://github.com/Azure/autorest.testserver/search?q=allowedValueEnum), [`animalNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=animalNotFoundError), [`expectedEnum`](https://github.com/Azure/autorest.testserver/search?q=expectedEnum), [`expectedNoErrors`](https://github.com/Azure/autorest.testserver/search?q=expectedNoErrors), [`expectedPetHungryError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetHungryError), [`expectedPetSadError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetSadError), [`getEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferenced), [`getEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferencedConstant), [`intError`](https://github.com/Azure/autorest.testserver/search?q=intError), [`linkNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=linkNotFoundError), [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated), [`putComplexPolymorphismNoDiscriminator`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismNoDiscriminator), [`putEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferenced), [`putEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferencedConstant), [`roundTripEnum`](https://github.com/Azure/autorest.testserver/search?q=roundTripEnum), [`stringError`](https://github.com/Azure/autorest.testserver/search?q=stringError), [`unexpectedEnum`](https://github.com/Azure/autorest.testserver/search?q=unexpectedEnum)</p></details>

## ❌️ Azure: 99%

<details><summary>1 out of 118 features are not covered by tests</summary><p>

[`LRONonRetryPut201Creating400InvalidJson`](https://github.com/Azure/autorest.testserver/search?q=LRONonRetryPut201Creating400InvalidJson)</p></details>

**Comment by RikkiGibson** [comment]
The windows failure is not due to something on our side so ignore that for now

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.4.2*

## ❌️ General: 94%

<details><summary>27 out of 535 features are not covered by tests</summary><p>

[`HttpRedirect301Put`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect301Put), [`HttpRedirect302Patch`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect302Patch), [`UrlQueriesArrayMultiEmpty`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiEmpty), [`UrlQueriesArrayMultiNull`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiNull), [`UrlQueriesArrayMultiValid`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiValid), [`additionalPropertiesInProperties`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInProperties), [`additionalPropertiesInPropertiesWithAPTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInPropertiesWithAPTypeString), [`additionalPropertiesTrue`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTrue), [`additionalPropertiesTypeObject`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeObject), [`additionalPropertiesTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeString), [`allowedValueEnum`](https://github.com/Azure/autorest.testserver/search?q=allowedValueEnum), [`animalNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=animalNotFoundError), [`expectedEnum`](https://github.com/Azure/autorest.testserver/search?q=expectedEnum), [`expectedNoErrors`](https://github.com/Azure/autorest.testserver/search?q=expectedNoErrors), [`expectedPetHungryError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetHungryError), [`expectedPetSadError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetSadError), [`getEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferenced), [`getEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferencedConstant), [`intError`](https://github.com/Azure/autorest.testserver/search?q=intError), [`linkNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=linkNotFoundError), [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated), [`putComplexPolymorphismNoDiscriminator`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismNoDiscriminator), [`putEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferenced), [`putEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferencedConstant), [`roundTripEnum`](https://github.com/Azure/autorest.testserver/search?q=roundTripEnum), [`stringError`](https://github.com/Azure/autorest.testserver/search?q=stringError), [`unexpectedEnum`](https://github.com/Azure/autorest.testserver/search?q=unexpectedEnum)</p></details>

## ❌️ Azure: 99%

<details><summary>1 out of 118 features are not covered by tests</summary><p>

[`LRONonRetryPut201Creating400InvalidJson`](https://github.com/Azure/autorest.testserver/search?q=LRONonRetryPut201Creating400InvalidJson)</p></details>

**Comment by RikkiGibson** [comment]
:tada: :tada:

**Pull request merged**
